modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="tardif_mod"
version="2.0.0"
displayName="TARDIF Mod"
displayURL="https://www.youtube.com/@Maketendo"
logoFile="logo.png"
credits="Teab02, We_Stan_Krang, Crimbo and Many of the Fam"
authors="Maketendo"
description="The TARDIF Mod has Materialised into Minecraft Forge!"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tardif_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration